import { Layout } from '@/components';
import { Page, useAuth } from '@/modules/auth';
import { Button, Toast } from 'flowbite-react';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const Home: NextPage = () => {
	const { logout } = useAuth();

	const handleLogout = React.useCallback(() => {
		void logout();
	}, [logout]);

	return (
		<Page.Authorized>
			<Layout>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
			</Layout>
		</Page.Authorized>
	);
};

export default Home;
