import { getClient } from '@/api/clients/axiosClient';
import { AuthorizedPage, useAuth } from '@/modules/auth';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const Home: NextPage = () => {
	const { logout } = useAuth();

	const handleLogout = React.useCallback(() => {
		void logout();
	}, [logout]);

	React.useEffect(() => {
		const testFetch = async () => {
			const client = getClient();

			const response = await client.get('/test');

			console.log(response.headers);
		};

		void testFetch();
	}, []);

	return (
		<AuthorizedPage>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				HomePage
				<button onClick={handleLogout}>Logout</button>
			</main>
		</AuthorizedPage>
	);
};

export default Home;
